title: "Callum Height - Lvl 0 SOC Analyst Ramblings"
description: "Project Work, Malware Analysis, Threat Hunting/Intel, Pentesting, CTFs, Privacy content and Scripts you'll never use"

remote_theme: "mmistakes/minimal-mistakes@master"

minimal_mistakes_skin: "default"

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-paginate

locale: "en-US"
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter_opts:
    block:
      line_numbers: false

author:
  name: "Callum Height"
  avatar: "/assets/images/me.png"
  bio: "Project Work, Malware Analysis, Threat Hunting/Intel, Pentesting, CTFs, Privacy content and Scripts you'll never use"
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/callum-height-671420181/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/lvl0socanalyst"

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      show_date: true

category_archive:
  type: liquid
  path: /categories/